# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: mysql2 
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: terraform-20240903085622721500000004
  username: admin
  password: veryStrongpassword1
  host: terraform-20240903085622721500000004.cjgi4cu0y5dc.ap-northeast-1.rds.amazonaws.com
  port: 3306
